<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LMPITSJ8NH6Q3" failures="1" tests="7" name="tests.myDetails.demoHoliday" time="71.607" errors="0" timestamp="2022-12-22T11:19:02 IST" skipped="0">
  <testcase classname="tests.myDetails.demoHoliday" name="myHolidayList" time="25.377"/>
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateMyHolidayList" time="2.143"/>
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateYellowHolidays" time="0.052"/>
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateSelectedHolidays" time="2.354"/>
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateSubmittedHolidayList" time="4.624">
    <failure message="Submitted holiday count not matched with balance count expected [2] but found [1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Submitted holiday count not matched with balance count expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at tests.myDetails.demoHoliday.pendingCountAfterSubmit(demoHoliday.java:232)
at tests.myDetails.demoHoliday.validateSubmittedHolidayList(demoHoliday.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateSubmittedHolidayList -->
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateUserLogout" time="6.875"/>
  <system-out/>
  <testcase classname="tests.myDetails.demoHoliday" name="validateMgrHolidayReqFlow" time="30.182"/>
  <system-out/>
</testsuite> <!-- tests.myDetails.demoHoliday -->
